### ISSUE TITLE
Right click "Squiddio hide all"

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#150]
I would like to have this option in the right click menu too.

**Comment by mauroc** [comment]
Rick - just to make sure I understand:  right now there is no option to "hide all" anywhere in the plugin . You can only go to squiddio->preferences and manually unselect all types of poi one by one.  

There is a "Hide local POIs" in the contextual (right-click) menu, which hides the POIs in the local sector but leaves the other ones visible. I suppose we could add a 'hilde all" entry to that menu. Is this what you are suggesting?

Since one of the complaints about the  plugin in the past has been that it takes too much precious real estate in the contextual menu, I wonder if we should just replace the 'hide local' with 'hide all'. Not sure how often users just want to hide pois in a specific sector and leave the other ones visible. Interested in your (or anyone's) thoughts...

**Comment by rgleason** [comment]
Mauro, I would agree with that.  I will often have several regions shown. When I want to check or do something else hide local does not take care of it for me (and probably others).  So then my choice is to diable squiddio which is not as convenient.

**Comment by rgleason** [comment]
Ps merey xmas.

**Comment by mauroc** [comment]
sounds like a valid request. I will try to implement at the next opportunity . Marry Xmas to you too.
